export const INTERESTS_1 = [
    { id: 31, label: 'Mountain Biking' },
    { id: 32, label: 'Snowmobiling' },
    { id: 33, label: 'Painting' },
    { id: 34, label: 'Grilling' },
    { id: 35, label: 'Surf Fishing' },
    { id: 36, label: 'Bartending' },
    { id: 37, label: 'Stamp Collecting' },
    { id: 38, label: 'Helping The Homeless' },
    { id: 39, label: 'Motorcycling' },
    { id: 40, label: 'Bicycle' },
    { id: 41, label: 'Gardening' },
    { id: 42, label: 'Golf' },
    { id: 43, label: 'Farming' },
    { id: 44, label: 'Growing Bonsais' },
    { id: 45, label: 'Meteorology' },

];

export const INTERESTS_3 = [
    { id: 46, label: 'Study' },
    { id: 47, label: 'Graphology' },
    { id: 48, label: 'Tea Drinking' },
    { id: 49, label: 'Fishing' },
    { id: 50, label: 'Rock Balancing' },
    { id: 51, label: 'Antiquing' },
    { id: 52, label: 'Exercising' },
    { id: 53, label: 'Raising Animals' },
    { id: 54, label: 'Investing' },
    { id: 55, label: 'Fantasy Sports' },
    { id: 56, label: 'Fencing' },
    { id: 57, label: 'Sky Diving' },
    { id: 58, label: 'Board Surfing' },
    { id: 59, label: 'Board Surfing' },
    { id: 60, label: 'Karate' },
]
export const INTERESTS = [
    { id: 1, label: 'Writing/Blogging' },
    { id: 2, label: 'Market Shopping' },
    { id: 3, label: 'Music' },
    { id: 4, label: 'Food' },
    { id: 5, label: 'Cooking' },
    { id: 6, label: 'Bartending' },
    { id: 7, label: 'Programming' },
    { id: 8, label: 'Tattooing' },
    { id: 9, label: 'Comedy' },
    { id: 10, label: 'Graphic Design' },
    { id: 11, label: 'YouTube' },
    { id: 12, label: 'Pet' },
    { id: 13, label: 'Facebook' },
    { id: 14, label: 'Yoga' },
    { id: 15, label: 'Cartooning' },

];

export const INTERESTS_2 = [
    { id: 16, label: 'Sport' },
    { id: 17, label: 'Game' },
    { id: 18, label: 'Fashion' },
    { id: 19, label: 'Travel' },
    { id: 20, label: 'Book' },
    { id: 21, label: 'Singing' },
    { id: 22, label: 'Playing Chess' },
    { id: 23, label: 'Boxing' },
    { id: 24, label: 'Working Out' },
    { id: 25, label: 'Weight Lifting' },
    { id: 26, label: 'Fencing' },
    { id: 27, label: 'Rock Climbing' },
    { id: 28, label: 'Hiking' },
    { id: 29, label: 'Architecture' },
    { id: 30, label: 'Beat Box' },
]